# Generated by Django 4.2.3 on 2023-12-20 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("DataEntry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exposure3",
            name="participant_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataEntry.participant"
            ),
        ),
        migrations.AddField(
            model_name="exposure2",
            name="participant_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataEntry.participant"
            ),
        ),
        migrations.AddField(
            model_name="exposure",
            name="participant_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataEntry.participant"
            ),
        ),
        migrations.AddField(
            model_name="ct_scan_nodule_5",
            name="participant_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataEntry.participant"
            ),
        ),
        migrations.AddField(
            model_name="ct_scan_nodule_4",
            name="participant_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataEntry.participant"
            ),
        ),
        migrations.AddField(
            model_name="ct_scan_nodule_3",
            name="participant_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataEntry.participant"
            ),
        ),
        migrations.AddField(
            model_name="ct_scan_nodule_2",
            name="participant_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataEntry.participant"
            ),
        ),
        migrations.AddField(
            model_name="ct_scan_nodule_1",
            name="participant_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataEntry.participant"
            ),
        ),
        migrations.AddField(
            model_name="ct_scan",
            name="airways_type",
            field=models.ManyToManyField(blank=True, to="DataEntry.airways_type"),
        ),
        migrations.AddField(
            model_name="ct_scan",
            name="cat_5_findings",
            field=models.ManyToManyField(blank=True, to="DataEntry.cat_5_findings"),
        ),
        migrations.AddField(
            model_name="ct_scan",
            name="copd_emphysema_type",
            field=models.ManyToManyField(blank=True, to="DataEntry.emphysema_type"),
        ),
        migrations.AddField(
            model_name="ct_scan",
            name="participant_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataEntry.participant"
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataEntry.question"
            ),
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="participant_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataEntry.participant"
            ),
        ),
        migrations.AddField(
            model_name="blood_collection",
            name="participant_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataEntry.participant"
            ),
        ),
        migrations.AddField(
            model_name="biological_relatives_with_cancer",
            name="mandatory_questionaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="DataEntry.mandatory_questionaire",
            ),
        ),
        migrations.AddField(
            model_name="annual_study_update_part_b",
            name="participant_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataEntry.participant"
            ),
        ),
        migrations.AddField(
            model_name="annual_study_update_part_a",
            name="participant_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataEntry.participant"
            ),
        ),
        migrations.AddField(
            model_name="annual_study_update_medications",
            name="participant_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataEntry.participant"
            ),
        ),
        migrations.AddField(
            model_name="annual_study_update",
            name="participant_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DataEntry.participant"
            ),
        ),
    ]
