# Generated by Django 4.2.3 on 2024-01-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0005_alter_mandatory_questionaire_biological_relatives_cancer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mandatory_questionaire", name="biological_relatives_cancer",
        ),
    ]
