# Generated by Django 4.2.3 on 2024-01-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0007_indirect_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirect_costs',
            name='procedure_other',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
