# Generated by Django 4.2.3 on 2024-01-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0009_indirect_costs_affected_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirect_costs',
            name='appointment_time_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='Hours'),
        ),
        migrations.AlterField(
            model_name='indirect_costs',
            name='appointment_time_minutes',
            field=models.FloatField(blank=True, null=True, verbose_name='Minutes'),
        ),
        migrations.AlterField(
            model_name='indirect_costs',
            name='babysitter_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='indirect_costs',
            name='other_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='indirect_costs',
            name='parking_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='indirect_costs',
            name='public_transportation_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='indirect_costs',
            name='transportation',
            field=models.TextField(choices=[('private', 'Private: (car)'), ('public', 'Public transportation (bus, metro, train, taxi)')], default=None, max_length=50, verbose_name='What means of transportation did you use to come to this appointment?'),
        ),
    ]
