# Generated by Django 4.2.3 on 2023-11-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0002_annual_study_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annual_study_update",
            name="biopsy_chest_lung",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="biopsy_chest_lung_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="bronchoscopy",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="bronchoscopy_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="checked_by",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="checked_by_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="chest_mri",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="chest_mri_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="chest_xray",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="chest_xray_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="cigs_per_day",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="cigs_per_day_amount",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="completed_form",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Participant", "Participant"),
                    (
                        "Participant with assistance from other person",
                        "Participant with assistance from other person",
                    ),
                    (
                        "Proxy (family member or friend), participant unable to provide information",
                        "Proxy (family member or friend), participant unable to provide information",
                    ),
                ],
                max_length=75,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="ct_scan_chest",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="ct_scan_chest_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="ct_scan_heart",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="ct_scan_heart_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="current_smoker",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="date_completed",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="fam_doc_cig_smoking",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="fam_doc_counselling",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="fam_doc_fuvisit",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="fam_doc_nic_replacement",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="fam_doc_stop_smoking",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="followup_time_period",
            field=models.TextField(
                blank=True,
                choices=[
                    ("1Y", "1Y"),
                    ("2Y", "2Y"),
                    ("3Y", "3Y"),
                    ("4Y", "4Y"),
                    ("5Y", "5Y"),
                    ("6Y", "6Y"),
                    ("7Y", "7Y"),
                    ("8Y", "8Y"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="gp_address",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="gp_fax",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="gp_msp",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="gp_name",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="gp_telephone",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="gp_visit",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="heart_disease_heart_info",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="heart_disease_heat_attack",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="heart_disease_heat_attack_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="high_cholerstrol_info",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="high_cholesterol",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="high_cholestrol_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="lung_cancer_chemo",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="lung_cancer_chemo_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="lung_cancer_diagnosis",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="lung_cancer_diagnosis_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="lung_cancer_diagnosis_info",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="lung_cancer_radiation",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="lung_cancer_radiation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="lung_cancer_treatment",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="lung_cancer_treatment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="lung_cancer_treatment_info",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="lung_chest_care",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="lung_chest_care_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="lung_chest_care_info",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="medication_dose",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="medication_frequency",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="medication_last_taken",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="medication_name",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="medication_reason",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="medication_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="new_meds_cholestrol",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="new_meds_cholestrol_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="new_meds_cholestrol_info",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="nuclear_scan",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="nuclear_scan_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="other_cancer_diagnosis",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="other_cancer_diagnosis_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="other_cancer_diagnosis_info",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="other_condition_diagnosis",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="other_condition_diagnosis_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="other_condition_diagnosis_info",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="other_lung_cancer_treatment",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="other_lung_cancer_treatment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="other_lung_cancer_treatment_info",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="other_medical_procedures",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="other_medical_procedures_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="other_medical_procedures_info",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="past_yr_cessation_program",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="past_yr_cessation_program_study",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="past_yr_champix",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="past_yr_ecigs",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="past_yr_ecigs_nic",
            field=models.TextField(
                blank=True,
                choices=[
                    ("With Nicotine", "With Nicotine"),
                    ("Without Nicotine", "Without Nicotine"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="past_yr_nic_replacement",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Nicotine Patches", "Nicotine Patches"),
                    ("Nicotine Gum", "Nicotine Gum"),
                    ("Nicotine Nasal Spray", "Nicotine Nasal Spray"),
                    ("Nicotine Lozenges", "Nicotine Lozenges"),
                    ("None", "None"),
                    ("N/A", "N/A"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="past_yr_quit_24hrs",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="past_yr_quit_24hrs_length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="past_yr_smoke_councellor",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="past_yr_smoke_councellor_info",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="past_yr_zyban",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="person_assisted",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="person_assisted_other",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="pet_scan",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="pet_scan_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="regular_family_doc",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="smoked_past_12_months",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="surgery_chest_lung",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="surgery_chest_lung_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="update_end_sate",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="annual_study_update",
            name="update_starting_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
