# Generated by Django 4.2.3 on 2023-11-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0003_alter_annual_study_update_biopsy_chest_lung_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plco_score",
            name="age",
            field=models.TextField(default=12, max_length=20),
            preserve_default=False,
        ),
    ]
