# Generated by Django 4.2.3 on 2023-11-30 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0004_plco_score_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="last_mandatory_questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "second_hand_smoke",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("Zero", "Zero"),
                            ("Mild", "Mild"),
                            ("Moderate", "Moderate"),
                            ("Heavy", "Heavy"),
                            ("N/A", "N/A"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "second_hand_home",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("Exposure at Home", "Exposure at Home"),
                            ("Exposure at Work", "Exposure at Work"),
                            (
                                "Exposure During leisure activities",
                                "Exposure During leisure activities",
                            ),
                            ("N/A", "N/A"),
                        ],
                        max_length=34,
                        null=True,
                    ),
                ),
                (
                    "second_hand_work",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "second_hand_leisure",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "second_hand_4days",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "second_hand_13days",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "second_hand_occasionally",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "second_hand_exposure_time",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("Less than 2 hours", "Less than 2 hours"),
                            ("2-4 hours", "2-4 hours"),
                            ("4-6 hours", "4-6 hours"),
                            ("6 plus hours", "6 plus hours"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "second_hand_yrs",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "second_hand_freq",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "second_hand_avg_exposure",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "second_hand_youth",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("Zero", "Zero"),
                            ("Mild", "Mild"),
                            ("Moderate", "Moderate"),
                            ("Heavy", "Heavy"),
                            ("N/A", "N/A"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "alcohol_from_age1",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_to_age1",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_beer1",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_wine1",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_liquor1",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_from_age2",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_to_age2",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_beer2",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_wine2",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_liquor2",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_from_age3",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_to_age3",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_beer3",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_wine3",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_liquor3",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_from_age4",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_to_age4",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_beer4",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_wine4",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_liquor4",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "alcohol_stop_age",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "second_hand_1yr",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("alcohol", models.TextField(blank=True, null=True)),
                ("alcohol_current", models.TextField(blank=True, null=True)),
                (
                    "second_hand_daily",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "inhaled_drugs",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "inhaled_drugs_day",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "inhaled_drugs_month",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "inhaled_drugs_year",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "inhaled_drugs_freq",
                    models.TextField(
                        blank=True,
                        choices=[
                            (
                                "Less than 1 time per month",
                                "Less than 1 time per month",
                            ),
                            ("1 - 3 times per month", "1 - 3 times per month"),
                            ("1 - 2 times per month", "1 - 2 times per month"),
                            ("3 - 6 times per month", "3 - 6 times per month"),
                            ("7 or more times per week", "7 or more times per week"),
                            ("N/A", "N/A"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "bronchodialators",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "bronchodialators_day",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "bronchodialators_month",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "bronchodialators_year",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "bronchodialators_freq",
                    models.TextField(
                        blank=True,
                        choices=[
                            (
                                "Less than 1 time per month",
                                "Less than 1 time per month",
                            ),
                            ("1 - 3 times per month", "1 - 3 times per month"),
                            ("1 - 2 times per month", "1 - 2 times per month"),
                            ("3 - 6 times per month", "3 - 6 times per month"),
                            ("7 or more times per week", "7 or more times per week"),
                            ("N/A", "N/A"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("statins", models.TextField(blank=True, max_length=20, null=True)),
                ("statins_day", models.TextField(blank=True, max_length=20, null=True)),
                (
                    "statins_month",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "statins_year",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "statins_freq",
                    models.TextField(
                        blank=True,
                        choices=[
                            (
                                "Less than 1 time per month",
                                "Less than 1 time per month",
                            ),
                            ("1 - 3 times per month", "1 - 3 times per month"),
                            ("1 - 2 times per month", "1 - 2 times per month"),
                            ("3 - 6 times per month", "3 - 6 times per month"),
                            ("7 or more times per week", "7 or more times per week"),
                            ("N/A", "N/A"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("metformin", models.TextField(blank=True, max_length=20, null=True)),
                (
                    "metformin_day",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "metformin_month",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "metformin_year",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "metformin_freq",
                    models.TextField(
                        blank=True,
                        choices=[
                            (
                                "Less than 1 time per month",
                                "Less than 1 time per month",
                            ),
                            ("1 - 3 times per month", "1 - 3 times per month"),
                            ("1 - 2 times per month", "1 - 2 times per month"),
                            ("3 - 6 times per month", "3 - 6 times per month"),
                            ("7 or more times per week", "7 or more times per week"),
                            ("N/A", "N/A"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "current_working_situation",
                    models.TextField(
                        choices=[
                            ("Working", "Working"),
                            ("Retired", "Retired"),
                            ("Unemployed", "Unemployed"),
                            ("Disabled", "Disabled"),
                            ("On extended sick leave", "On extended sick leave"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "current_working_situation_other",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "occupation_longest",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "occupation_longest_activities",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "occupation_longest_years",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "occupation_exposure",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                (
                    "occupation_fumes",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                ("occupation_years", models.TextField(blank=True, null=True)),
                (
                    "participant_num",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataEntry.participant",
                    ),
                ),
            ],
        ),
    ]
