# Generated by Django 4.2.1 on 2023-06-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0006_alter_lab_processing_casper_caps_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lab_processing",
            name="da_hs_l_date",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="da_hs_l_int_std",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="da_hs_l_method",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="da_hs_l_spiked",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="da_hs_l_wbrush_date",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="da_hs_l_wbrush_int_std",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="da_hs_l_wbrush_method",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="da_hs_l_wbrush_spiked",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="da_hs_r_date",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="da_hs_r_int_std",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="da_hs_r_method",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="da_hs_r_spiked",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="da_hs_r_wbrush_date",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="da_hs_r_wbrush_int_std",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="da_hs_r_wbrush_method",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="da_hs_r_wbrush_spiked",
            field=models.TextField(max_length=20),
        ),
    ]
