# Generated by Django 4.2.1 on 2023-06-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "DataEntry",
            "0011_exposure3_remove_exposure2_home_1_avg_monthly_stay_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(name="Exposure2",),
        migrations.DeleteModel(name="Exposure3",),
        migrations.DeleteModel(name="lab_processing2",),
        migrations.AddField(
            model_name="breath_collection",
            name="casper_caps",
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="casper_purge",
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="casper_spiked",
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="casper_storage",
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="int_std_sln",
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="int_std_sln_vol",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="micro_int_std_sln",
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="micro_int_std_vol",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="reciva_caps",
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="reciva_purge",
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="reciva_spiked",
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="reciva_storage",
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="room_air_caps",
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="room_air_purge",
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="room_air_spiked",
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="room_air_storage",
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="sweat_caps",
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="breath_collection",
            name="sweat_location",
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
